---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: logstash
  name: logstash
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: logstash
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - image: docker.elastic.co/logstash/logstash:7.0.0
          imagePullPolicy: Always
          name: logstash
          ports:
            - containerPort: 5044
              name: 5044tcp02
              protocol: TCP
            - containerPort: 9600
              name: 9600tcp02
              protocol: TCP
            - containerPort: 5044
              name: 5044tcp305441
              protocol: TCP
            - containerPort: 9600
              name: 9600tcp305961
              protocol: TCP
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            procMount: Default
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          volumeMounts:
            - mountPath: /usr/share/logstash/config
              name: logstash-config
            - mountPath: /usr/share/logstash/pipeline
              name: logstash-pipelines-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: logstash-config
            optional: false
          name: logstash-config
        - configMap:
            defaultMode: 420
            name: logstash-pipelines-config
            optional: false
          name: logstash-pipelines-config
---